name: check
on: push
jobs:
  check:
    env:
      MIX_ENV: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 23.0
          elixir-version: 1.10.3
      - uses: actions/cache@v2
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix format --check-formatted
        if: always()
      - run: mix sobelow --config
        if: always()
      - run: mix credo
        if: always()
      - run: mix dialyzer
        if: always()
      - run: mix coveralls.json
        if: always()
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./cover/excoveralls.json
